# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_mobile_ad_preview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previewinfo',
            name='call_to_action',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
