# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_mobile_ad_preview', '0002_auto_20170424_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previewinfo',
            name='call_to_action',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
