# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_mobile_ad_preview', '0003_auto_20170424_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='previewinfo',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
